-- ─────────────────────────────────────────────────────────────────────────────
-- Wards table for RotaManager
-- Run this once in the Supabase SQL editor (Dashboard → SQL Editor → New query).
-- Safe to re-run: uses IF NOT EXISTS / ON CONFLICT.
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.wards (
  id               bigint generated by default as identity primary key,
  name             text        not null unique,
  department       text        not null,
  nursing_weeks    integer     not null default 0 check (nursing_weeks >= 0),
  midwifery_weeks  integer     not null default 0 check (midwifery_weeks >= 0),
  capacity         integer              check (capacity is null or capacity > 0),
  sort_order       integer     not null default 0,
  created_at       timestamptz not null default now()
);

alter table public.wards enable row level security;

-- Everyone signed in can read wards (members, in-charges, admins).
drop policy if exists "wards_select_authenticated" on public.wards;
create policy "wards_select_authenticated"
  on public.wards for select
  to authenticated
  using (true);

-- Only admins (anyone whose role is not Member / In-charge) can write.
drop policy if exists "wards_write_admin" on public.wards;
create policy "wards_write_admin"
  on public.wards for all
  to authenticated
  using      (coalesce(auth.jwt() -> 'user_metadata' ->> 'role', 'Member') not in ('Member', 'In-charge'))
  with check (coalesce(auth.jwt() -> 'user_metadata' ->> 'role', 'Member') not in ('Member', 'In-charge'));

-- Realtime updates so every open dashboard refreshes automatically.
do $$
begin
  alter publication supabase_realtime add table public.wards;
exception when duplicate_object then null;
end $$;

-- Seed with the wards that were previously hard-coded in the app.
insert into public.wards (name, department, nursing_weeks, midwifery_weeks, sort_order) values
  ('Emergency',                     'Medical',          3,  2,  10),
  ('Males'' Ward',                  'Medical',          3,  2,  20),
  ('Females'' Ward',                'Medical',          3,  2,  30),
  ('Paediatric Ward',               'Medical',          3,  2,  40),
  ('OPD',                           'Medical',          0,  2,  50),
  ('Surgical Ward',                 'Surgical',         4,  2,  60),
  ('Theatre',                       'Surgical',         4,  2,  70),
  ('Recovery Ward',                 'Surgical',         4,  2,  80),
  ('Eye Clinic',                    'Special Clinics',  1,  1,  90),
  ('ENT',                           'Special Clinics',  2,  1, 100),
  ('Dental',                        'Special Clinics',  2,  1, 110),
  ('Dialysis',                      'Special Clinics',  1,  1, 120),
  ('Sickle Cell / HPT / DM Clinic', 'Special Clinics',  1,  0, 130),
  ('Isolation',                     'Special Clinics',  2,  0, 140),
  ('ANC/PNC Clinic',                'Obstetrics',       2,  6, 150),
  ('ANC/PNC Ward',                  'Obstetrics',       2,  4, 160),
  ('Labour Ward',                   'Obstetrics',       3, 12, 170),
  ('NCU',                           'Obstetrics',       3,  4, 180),
  ('Nutrition',                     'Public Health',    1,  0, 190),
  ('RCH',                           'Public Health',    2,  4, 200),
  ('HIV / ART Clinic',              'Public Health',    1,  0, 210),
  ('HIV / ART',                     'Public Health',    0,  2, 220),
  ('Nutrition & Health Promotion',  'Public Health',    0,  2, 230),
  ('Psychiatry',                    'Psychiatry',       8,  4, 240)
on conflict (name) do nothing;
